const filterHeading = [
  "Category",
  "Sizes",
  "Brand",
  "Design",
  "Fit",
  "Sleeve",
  "Neck",
  "Type",
  "Ratings",
  "Offers",
  "Discount",
  "Sort By",
];

const headingData = {
  Category: [
    "T-Shirt",
    "Boxer",
    "Shirt",
    "Shorts",
    "Vest",
    "Joggers",
    "Sweatshirt",
    "Hoodies",
    "Pyjama",
    "Co-Ordinates",
    "Jeans",
    "Jacket",
    "Track Pant",
    "Sweater",
    "Trousers",
    "Pant",
    "Casual Pants",
    "Kurta",
    "Protective Outdoor Mask",
    "Sweatshirt & Jogger Set",
    "Cloth Mask",
  ],
  Sizes: [
    "XS",
    "S",
    "M",
    "L",
    "XL",
    "2XL",
    "3XL",
    "4XL",
    "5XL",
    "28",
    "30",
    "32",
    "34",
    "36",
    "38",
    "40",
    "42",
    "44",
    "46",
    "48",
  ],
  Brand: [
    "Bewakoof®",
    "Bewakoof Air® 1.0",
    "Campus Sutra",
    "Xyxx",
    "Rigo",
    "Bewakoof Heavy Duty® 1.0",
    "Urban Scottish",
    "Bushirt",
    "What's Down",
    "Indiclub",
    "The Daily Outfits",
    "Vastrado",
    "Mad Over Print",
    "Rodamo",
    "Wearduds",
    "Chimpaaanzee",
    "Door 74",
    "Recast",
    "Bewakoof American Pima",
    "Flynoff",
    "7 Shores",
    "Difference Of Opinion",
    "Dillinger",
    "Shopolics",
    "Silisoul",
    "Smugglerz",
    "Chkokko",
    "East Coast Way",
    "Trends Tower",
    "Blanck",
    "Koovs",
    "Big Bunny",
    "The Dry State",
    "Olavi",
    "Fans Army",
    "Kranium",
    "Kotty",
    "Brown Mocha",
    "Harpita",
    "Vyve",
    "Botnia",
    "Dimeh",
    "Dropout Society",
    "Showoff",
    "The Bargain Street",
    "Brown Brothers",
    "Truebuyworld",
    "Vibebling",
  ],
  Design: [
    "Graphic Print",
    "Solid",
    "Printed",
    "Aop",
    "Typography",
    "Color Block",
    "Striped",
    "Checked",
    "Self Design",
    "Washed",
    "Tie & Dye",
    "Camouflage",
    "Floral Print",
    "Textured",
    "Embroidered",
    "Ombre",
    "Abstract",
    "Paisley",
    "Botanical",
    "Geometric Print",
    "Polka Print",
    "Animal Print",
    "Ethnic Motifs",
    "Marble Print",
    "Polka Dots",
  ],
  Fit: [
    "Regular Fit",
    "Oversized Fit",
    "Relaxed Fit",
    "Slim Fit",
    "Super Loose Fit",
    "Boxy Fit",
    "Loose Comfort Fit",
    "Straight Fit",
    "Wide Leg",
    "Monster Fit",
    "Square Fit",
    "Tapered Fit",
  ],
  Sleeve: [
    "Half Sleeve",
    "Full Sleeve",
    "Sleeveless",
    "Drop Shoulder",
    "Raglan Sleeve",
  ],
  Neck: [
    "Round Neck",
    "Hooded",
    "Spread Collar",
    "Collar",
    "Polo",
    "Resort Collar",
    "Lapel Collar",
    "V-Neck",
    "High Neck",
    "Stand Collar",
    "Mandarin Collar",
    "Henley Neck",
    "Scoop Neck",
    "Notch Collar",
    "Slim Collar",
    "Shawl Neck",
    "Turtle Neck",
  ],
  Type: [
    "T-Shirt",
    "Boxer",
    "Shirt",
    "Vest",
    "Shorts",
    "Sweatshirt",
    "Cargo",
    "Hoodies",
    "Joggers",
    "Pyjama",
    "Jeans",
    "Trackpants",
    "T-Shirt & Shorts Set",
    "Lounge Pants",
    "Polo",
    "Jacket",
    "Flat Knits",
    "Puffer Jacket",
    "Sweater",
    "Trousers",
    "Casual Pants",
    "Wind Cheater",
    "Sweatshirt & Jogger Set",
    "Shirt & Shorts Set",
    "Parachute Pants",
    "Co-Ordinates",
    "Chino",
    "T-Shirt & Casual Pants Set",
    "Shacket",
    "Sports Shorts",
    "T-Shirt & Jogger Set",
    "Cargo Shorts",
    "Pants",
    "Hoodie & Jogger Set",
    "Shirt & Casual Pants Set",
    "Bombers",
    "Carpenter",
    "Carpenter Pants",
    "Short Kurta",
    "Denim",
    "Long Kurta",
  ],
  Ratings: [
    "4.5 and above",
    "4 and above",
    "3.5 and above",
    "3 and above",
    "2.5 and above",
    "2 and above",
    "1.5 and above",
    "1 and above",
  ],
  Offers: ["Buy 3 For 1199"],
  Discount: [
    "10% Or More",
    "20% Or More",
    "30% Or More",
    "40% Or More",
    "50% Or More",
    "60% Or More",
    "70% Or More",
  ],
  "Sort By": ["Popular", "New", "Price : High to Low", "Price : Low to High"],
};

let data = {
  arr: [],

  listedData: function () {
    return filterHeading.map((ele) => ({
      [ele]: headingData[ele],
    }));
  },
};


export default data